// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { env } from "process";
// import { defineConfig, env } from "@prisma/config";


export default defineConfig({
  schema: "prisma/schema",   
  migrations: {
    path: "prisma/migrations",
  },
  
  datasource: {
    url: env["DATABASE_URL"], 
  },
});

function defineConfig(arg0: { schema: string; migrations: { path: string; }; datasource: { url: string | undefined; }; }) {
  throw new Error("Function not implemented.");
}
